version: '3.9'
services:
    php-apache:
        ports:
            - 80:80
        build: './build/php'
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db
        restart: always
        container_name: php-web
    db:
        container_name: mysql
        ports:
            - "3306:3306"
        build: './build/mysql'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123123
            MYSQL_DATABASE: personal
        volumes:
            - db-data:/var/lib/mysql:rw
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
          - '8080:80'
      restart: always
      environment:
          PMA_HOST: db
      depends_on:
          - db

volumes:
  db-data: